name: ATF Regression Suite

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Choose browser for automation suite:'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - edge
      suite:
        description: 'Choose automation suite:'
        required: true
        default: 'smokeSuite'
        type: choice
        options:
          - smokeSuite
          - regressionSuite


jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run automation tests
      run: mvn clean install -DciCd=true -Dbrowser=${{ github.event.inputs.browser }} -DsuiteXmlFile=suites/${{ github.event.inputs.suite }}.xml -P CustomSuite


      
